version: '3.7'
services:
  php:
    container_name: wordpress-education.local-prod
    image: 'defaultvalue/php:8.1-production'
    user: 'docker:docker'
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    restart: always
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.wordpress-education-local-http.rule=Host(`wordpress-education.local`,`www.wordpress-education.local`)'
      - traefik.http.routers.wordpress-education-local-http.entrypoints=http
      - traefik.http.routers.wordpress-education-local-http.service=wordpress-education-local-http
      - traefik.http.services.wordpress-education-local-http.loadbalancer.server.port=80
      - traefik.http.services.wordpress-education-local-http.loadbalancer.server.scheme=http
      - 'traefik.http.routers.wordpress-education-local-https.rule=Host(`wordpress-education.local`,`www.wordpress-education.local`)'
      - traefik.http.routers.wordpress-education-local-https.entrypoints=https
      - traefik.http.routers.wordpress-education-local-https.tls=true
      - traefik.http.routers.wordpress-education-local-https.service=wordpress-education-local-https
      - traefik.http.services.wordpress-education-local-https.loadbalancer.server.port=443
      - traefik.http.services.wordpress-education-local-https.loadbalancer.server.scheme=https
    extra_hosts:
      - 'wordpress-education.local www.wordpress-education.local:127.0.0.1'
    environment:
      - COMPOSER_VERSION=2
    volumes:
      - '../../:/var/www/html'
      - '${SSL_CERTIFICATES_DIR}:/certs'
      - './apache/virtual-host.conf:/etc/apache2/sites-enabled/000-default.conf:ro'
  mysql:
    image: 'mysql:8.0'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
      - 'mysql_prod_data:/var/lib/mysql'
      - './mysql/my.cnf:/etc/my.cnf:ro'
volumes:
  mysql_prod_data:
    external: false
